### ISSUE TITLE
Keep getting error

### ISSUE THREAD

**Issue by Freeman12112** [Re-Dream/discord_relay#6]
every time i edit the file is keeps give me a error but when i don't edit the file its fine

[ERROR] addons/discord_relay-master/lua/discord_relay/sv_config.lua:16: '<name>' expected near 'local'
  1. unknown - addons/discord_relay-master/lua/discord_relay/sv_config.lua:0
 
Woah, we couldn't find ourselves a config file! If this happens, you should reinstall.
[ERROR] addons/discord_relay-master/lua/discord_relay/sv_relay.lua:6: attempt to index global 'DiscordRelay' (a nil value)
  1. unknown - addons/discord_relay-master/lua/discord_relay/sv_relay.lua:6
   2. include - [C]:-1
    3. unknown - addons/discord_relay-master/lua/autorun/discord_relay_load.lua:5
 
[Discord] Hooray! Relay has been loaded!

**Comment by Freeman12112** [comment]
![38059228-a3873ca0-32b3-11e8-8d80-02934e9f8e17](https://user-images.githubusercontent.com/32149762/38059261-bc52632c-32b3-11e8-942f-3f6f0d82fd17.png)

Heres A Image Of The Error

**Comment by Tenrys** [comment]
Send me your config file somewhere, you have a syntax error.

**Comment by Freeman12112** [comment]
This is my config file
https://mega.nz/#!eFAChARa!qiAtxCUxCJNggzZiJDyxFO99oPAQcC3FoWo-gkm4K68

**Comment by Tenrys** [comment]
Don't modify the bot token and Steam web API values directly, create the `apikey.cfg` and `relay_bot_token.cfg` files in your `cfg` directory with the corresponding data instead.

So inside of `apikey.cfg` would just be `E1265FE0DBDA09868F7EC24A6F51799F`.

Although if you wanted to do it like that then you would have needed to make your values strings (surround them with double quotes) because currently this setup causes a syntax error.

Keep in mind you just made your bot's token and Steam web API key public by posting your file containing them here, meaning anyone that gets a hold of them here could be using it for malicious purposes if they wanted. I recommend you get a new one of each.

**Comment by Freeman12112** [comment]
thank you

**Comment by Freeman12112** [comment]
it worked thank you and what is the bot token do if its not using it

**Comment by Tenrys** [comment]
What do you mean? What is the add-on saying?

**Comment by Freeman12112** [comment]
no it works but on discord the bot is offline and i just see it using the web hook only

**Comment by Tenrys** [comment]
Not sure, it's like that for me too.

**Comment by Freeman12112** [comment]
k thanks for letting me know.
